
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  user: kanbujian
  password: post123456

development:
  <<: *default
  database: walden_development
  url: postgresql://127.0.0.1/walden_development?pool=5

test:
  <<: *default
  database: walden_test
  url: postgresql://127.0.0.1/walden_test?pool=5


production:
  <<: *default
  database: walden
